version: '3.8'

services:
  django_app:
    container_name: django_app
    build: .
    command: /bin/sh -c "python3 manage.py migrate &&
                      python3 manage.py spectacular --color --file schema.yml &&
                      python3 manage.py runserver 0.0.0.0:8000
                      "
    volumes:
      - .:/django_app
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - pg_db

  pg_db:
    container_name: pg_db
    image: postgres:14.6-alpine
    env_file:
      - .env
    restart: unless-stopped