openapi: 3.0.3
info:
  title: Softorium API
  version: 1.0.0
  description: api for magic ball
paths:
  /api/v1/ask_question/:
    post:
      operationId: ask_the_question
      description: Ask the question
      tags:
      - ask_question
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ask the question'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Ask the question'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Ask the question'
        required: true
      security:
      - basicAuth: []
      - tokenAuth: []
      responses:
        '201':
          description: Success
        '400':
          description: No question
        '401':
          description: Incorrect authentication credentials.
        '403':
          description: Credentials weren't provided
        '404':
          description: Question does not exist
  /api/v1/get_history_questions/:
    get:
      operationId: get_history_questions
      description: Get history questions
      tags:
      - get_history_questions
      security:
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetQuestion'
          description: Success
        '204':
          description: You haven't any questions yet
        '401':
          description: Incorrect authentication credentials.
        '403':
          description: Credentials weren't provided
        '404':
          description: Question does not exist
components:
  schemas:
    Ask the question:
      type: object
      properties:
        question:
          type: string
      required:
      - question
    GetQuestion:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        total:
          type: integer
        text:
          type: string
          maxLength: 255
        answer:
          type: string
          maxLength: 255
        asked_at:
          type: string
          format: date-time
          readOnly: true
        user:
          type: integer
      required:
      - asked_at
      - id
      - text
      - user
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
